name: Build Docker Image (Local Simulation)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-webapp .
name: Build Docker Image (Local Simulation)

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-webapp .
